# Where things are
source              : .
destination         : ./_site
collections_dir     : .
plugins_dir         : _plugins
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
collections:
  posts:
    output          : true
  members:
    output          : true
    people          : true
  workshops:
    output          : true
  jobs:
    output          : true
